name: SmokeAliyunECS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      GIT_SHA: ${{ github.sha }}
      GIT_REF_NAME: ${{ github.ref_name }}
      GIT_REPO: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install ssh-scp
        run: sudo apt-get install -y openssh-client

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Get build time
        id: build-time
        run: echo "buildTime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Build
        env:
          CGO_ENABLED: "1"
          GOARCH: "amd64"
          GIT_SHA: ${{ github.sha }}
          GIT_REF_NAME: ${{ github.ref_name }}
          GIT_REPO: ${{ github.repository }}
        run: |
          echo "Building Go application with gitHash=${{ env.gitHash }} and buildTime=${{ env.buildTime }}"
          go build -ldflags="-X 'main.gitHash=${{ github.sha }}' -X 'main.buildTime=${{ env.buildTime }}'" -o unchain .

      - name: Deploy to AliCloud ECS
        env:
          SSH_HOST: ${{ secrets.ECS_HOST }}
          SSH_USER: ${{ secrets.ECS_USER }}
          SSH_KEY: ${{ secrets.ECS_KEY }}
          ENV_VARS: ${{ vars.ENV_VARS }}
        run: bash .github/workflows/deploy.sh
#       add more server to deploy
